# Generated by Django 4.2.28 on 2026-03-09 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('spotify_preview_url', models.URLField(blank=True, help_text='Direct link to  audio clip', null=True)),
                ('lyrics', models.TextField()),
                ('difficulty_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('root_form', models.CharField(blank=True, max_length=100, null=True)),
                ('distractor_1', models.CharField(blank=True, help_text='Wrong answer 1', max_length=100)),
                ('distractor_2', models.CharField(blank=True, help_text='Wrong answer 2', max_length=100)),
                ('distractor_3', models.CharField(blank=True, help_text='Wrong answer 3', max_length=100)),
                ('related_songs', models.ManyToManyField(related_name='vocabulary', to='core.song')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(default='Spanish', max_length=50)),
                ('proficiency_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('favorite_genres', models.CharField(blank=True, max_length=200)),
                ('current_streak', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_level', models.IntegerField(default=0)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vocabulary')),
            ],
            options={
                'unique_together': {('user', 'vocabulary')},
            },
        ),
    ]
