# Generated by Django 4.2.28 on 2026-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_daysactive_genre_genreselection_language_playlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='foreign_word',
            new_name='word_text',
        ),
        migrations.RemoveField(
            model_name='song',
            name='clip_preview_url',
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_preview_url',
            field=models.URLField(blank=True, help_text='Direct link to  audio clip', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='proficiency_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='proficiency_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='proficiency_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='word',
            name='proficiency_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
    ]
