# Generated by Django 4.2.28 on 2026-03-22 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_song_primary_genre_alter_song_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daysactive',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='genreselection',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='usersongs',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='userwords',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
    ]
