# Generated by Django 4.2.28 on 2026-03-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_primary_genre_song_genre_delete_songgenres'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist', to='core.genre'),
        ),
        migrations.DeleteModel(
            name='PlaylistGenres',
        ),
    ]
