# Generated by Django 4.2.28 on 2026-03-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_playlist_genre_delete_playlistgenres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='num_listens',
            new_name='num_days_listened',
        ),
        migrations.AddField(
            model_name='playlist',
            name='last_date_played',
            field=models.DateField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='PlaylistDaysListened',
        ),
    ]
