# Generated by Django 4.2.28 on 2026-03-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_num_listens_playlist_num_days_listened_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='last_date_played',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
