# Generated by Django 4.2.28 on 2026-03-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_playlist_last_date_played'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='creation_date',
            new_name='created_date',
        ),
    ]
