# Generated by Django 4.2.28 on 2026-04-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_playlistsong_usersong_userword_remove_usersongs_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
