# Generated by Django 4.2.28 on 2026-05-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_song_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist', to='core.genre'),
        ),
    ]
