# Generated by Django 4.2.28 on 2026-05-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_song', to='core.song'),
        ),
        migrations.AlterField(
            model_name='usersong',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='core.userprofile'),
        ),
    ]
