# Generated by Django 4.2.28 on 2026-05-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_spotifycredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
