# Generated by Django 4.2.28 on 2026-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_album_art_url_to_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifycredentials',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spotifycredentials',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
