# Generated by Django 4.2.28 on 2026-03-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenreSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_selections', to='core.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('proficiency_level', models.IntegerField(default=1)),
                ('num_listens', models.IntegerField(default=0)),
                ('num_song_listens', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='core.language')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistDaysListened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_listened', to='core.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_featuring', to='core.genre')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_genres', to='core.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='core.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='SongGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_entries', to='core.genre')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_listens', models.IntegerField(default=0)),
                ('num_lyric_challenges_completed', models.IntegerField(default=0)),
                ('mastery_lvl', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_listens', models.IntegerField(default=0)),
                ('num_practices_completed', models.IntegerField(default=0)),
                ('mastery_lvl', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_word', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('pronunciation', models.CharField(blank=True, max_length=200)),
                ('definition', models.TextField(blank=True)),
                ('proficiency_level', models.IntegerField(default=1)),
                ('lexical_category', models.CharField(blank=True, max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='core.language')),
            ],
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='related_songs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_preview_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_streak',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='song',
            name='clip_preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='proficiency_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='proficiency_level',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
        migrations.DeleteModel(
            name='Vocabulary',
        ),
        migrations.AddField(
            model_name='userwords',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='userwords',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='core.word'),
        ),
        migrations.AddField(
            model_name='usersongs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.song'),
        ),
        migrations.AddField(
            model_name='usersongs',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_songs', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='songgenres',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_genres', to='core.song'),
        ),
        migrations.AddField(
            model_name='playlistsongs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_contained_in', to='core.song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='genreselection',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_selections', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='daysactive',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_active', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='core.language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.language'),
        ),
    ]
