# Generated by Django 4.2.28 on 2026-03-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_foreign_word_word_word_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daysactive',
            old_name='user_profile',
            new_name='user_profile_id',
        ),
        migrations.RenameField(
            model_name='genreselection',
            old_name='user_profile',
            new_name='user_profile_id',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='user_profile',
            new_name='user_profile_id',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='user_profile',
            new_name='user_profile_id',
        ),
        migrations.RenameField(
            model_name='usersongs',
            old_name='user_profile',
            new_name='user_profile_id',
        ),
        migrations.RenameField(
            model_name='userwords',
            old_name='user_profile',
            new_name='user_profile_id',
        ),
    ]
