# Generated by Django 4.2.28 on 2026-03-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_profile_daysactive_user_profile_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='language',
            new_name='language_id',
        ),
        migrations.RenameField(
            model_name='playlistdayslistened',
            old_name='playlist',
            new_name='playlist_id',
        ),
        migrations.RenameField(
            model_name='playlistgenres',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='playlistgenres',
            old_name='playlist',
            new_name='playlist_id',
        ),
        migrations.RenameField(
            model_name='playlistsongs',
            old_name='playlist',
            new_name='playlist_id',
        ),
        migrations.RenameField(
            model_name='playlistsongs',
            old_name='song',
            new_name='song_id',
        ),
    ]
