# Generated by Django 4.2.28 on 2026-03-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_language_playlist_language_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='playlistdayslistened',
            old_name='playlist_id',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistgenres',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='playlistgenres',
            old_name='playlist_id',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistsongs',
            old_name='playlist_id',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistsongs',
            old_name='song_id',
            new_name='song',
        ),
    ]
