# Generated by Django 4.2.28 on 2026-03-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_language_id_playlist_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='primary_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song', to='core.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='core.language'),
        ),
    ]
