# Generated by Django 4.2.28 on 2026-03-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_user_profile_id_daysactive_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='primary_genre',
            new_name='genre',
        ),
        migrations.DeleteModel(
            name='SongGenres',
        ),
    ]
