# Generated by Django 4.2.28 on 2026-03-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_creation_date_playlist_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_song', to='core.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_contained_in', to='core.song')),
            ],
        ),
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_listens', models.IntegerField(default=0)),
                ('num_lyric_challenges_completed', models.IntegerField(default=0)),
                ('mastery_lvl', models.IntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.song')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_song', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_listens', models.IntegerField(default=0)),
                ('num_practices_completed', models.IntegerField(default=0)),
                ('mastery_lvl', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to='core.userprofile')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to='core.word')),
            ],
        ),
        migrations.RemoveField(
            model_name='usersongs',
            name='song',
        ),
        migrations.RemoveField(
            model_name='usersongs',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userwords',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userwords',
            name='word',
        ),
        migrations.DeleteModel(
            name='PlaylistSongs',
        ),
        migrations.DeleteModel(
            name='UserSongs',
        ),
        migrations.DeleteModel(
            name='UserWords',
        ),
    ]
