name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # update only on main branch update

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/songlingo
            git pull
<<<<<<< HEAD
            docker compose build --no-cache
            docker compose up -d
            docker compose exec -T web python manage.py migrate
=======
            docker compose build --no-cache web
            docker compose up -d
>>>>>>> 01b873d7c9b2445411debeaddb96a84e26d08aee
